In [1]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

c:\Users\jaesc2\GitHub\skforecast


In [6]:
import numpy as np
import pandas as pd
from skforecast.ForecasterAutoregMultiSeries import ForecasterAutoregMultiSeries
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [7]:
# df 1000 series
np.random.seed(1)
n_series = 100
n = 100
index = pd.date_range(start='01-01-2010', periods=n, freq='D')
columns = ['series_' + str(i) for i in range(n_series)]
data = np.random.normal(loc=0, scale=1, size=(n, n_series))
df = pd.DataFrame(data, index=index, columns=columns)

columns_exog = ['exog_' + str(i) for i in range(n_series)]
data_exog = np.random.normal(loc=0, scale=1, size=(n, n_series))
df_exog = pd.DataFrame(data_exog, index=index, columns=columns_exog)

In [8]:
transformer_series = {col: StandardScaler() for col in columns}
transformer_series['_unknown_level'] = StandardScaler()

forecaster = ForecasterAutoregMultiSeries(
                    regressor = LinearRegression(),
                    lags = 5,
                    transformer_series = StandardScaler(),
                )
forecaster

============================ 
ForecasterAutoregMultiSeries 
============================ 
Regressor: LinearRegression() 
Lags: [1 2 3 4 5] 
Window features: None 
Window size: 5 
Series encoding: ordinal 
Series names (levels): None 
Exogenous included: False 
Exogenous names: None 
Transformer for series: StandardScaler() 
Transformer for exog: None 
Weight function included: False 
Series weights: None 
Differentiation order: None 
Training range: None 
Training index type: None 
Training index frequency: None 
Regressor parameters: 
    {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False} 
fit_kwargs: {} 
Creation date: 2024-10-16 16:57:04 
Last fit date: None 
Skforecast version: 0.14.0 
Python version: 3.12.4 
Forecaster id: None

In [9]:
forecaster.__repr__

<bound method ForecasterAutoregMultiSeries.__repr__ of ============================ 
ForecasterAutoregMultiSeries 
Regressor: LinearRegression() 
Lags: [1 2 3 4 5] 
Window features: None 
Window size: 5 
Series encoding: ordinal 
Series names (levels): None 
Exogenous included: False 
Exogenous names: None 
Transformer for series: StandardScaler() 
Transformer for exog: None 
Weight function included: False 
Series weights: None 
Differentiation order: None 
Training range: None 
Training index type: None 
Training index frequency: None 
Regressor parameters: 
    {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False} 
fit_kwargs: {} 
Creation date: 2024-10-16 16:57:04 
Last fit date: None 
Skforecast version: 0.14.0 
Python version: 3.12.4 
Forecaster id: None 
>

In [10]:
forecaster.fit(series=df, exog=df_exog)
forecaster

============================ 
ForecasterAutoregMultiSeries 
============================ 
Regressor: LinearRegression() 
Lags: [1 2 3 4 5] 
Window features: None 
Window size: 5 
Series encoding: ordinal 
Series names (levels): 
    series_0, series_1, series_2, series_3, series_4, series_5, series_6, series_7,
    series_8, series_9, series_10, series_11, series_12, series_13, series_14,
    series_15, series_16, series_17, series_18, series_19, series_20, series_21,
    series_22, series_23, series_24, ..., series_75, series_76, series_77,
    series_78, series_79, series_80, series_81, series_82, series_83, series_84,
    series_85, series_86, series_87, series_88, series_89, series_90, series_91,
    series_92, series_93, series_94, series_95, series_96, series_97, series_98,
    series_99 
Exogenous included: True 
Exogenous names: 
    exog_0, exog_1, exog_2, exog_3, exog_4, exog_5, exog_6, exog_7, exog_8, exog_9,
    exog_10, exog_11, exog_12, exog_13, exog_14, exog_15, exog_16, exog_17,
    exog_18, exog_19, exog_20, exog_21, exog_22, exog_23, exog_24, ..., exog_75,
    exog_76, exog_77, exog_78, exog_79, exog_80, exog_81, exog_82, exog_83,
    exog_84, exog_85, exog_86, exog_87, exog_88, exog_89, exog_90, exog_91,
    exog_92, exog_93, exog_94, exog_95, exog_96, exog_97, exog_98, exog_99 
Transformer for series: StandardScaler() 
Transformer for exog: None 
Weight function included: False 
Series weights: None 
Differentiation order: None 
Training range: 
    'series_0': ['2010-01-01', '2010-04-10'], 'series_1': ['2010-01-01',
    '2010-04-10'], 'series_2': ['2010-01-01', '2010-04-10'], 'series_3':
    ['2010-01-01', '2010-04-10'], 'series_4': ['2010-01-01', '2010-04-10'], ...,
    'series_95': ['2010-01-01', '2010-04-10'], 'series_96': ['2010-01-01',
    '2010-04-10'], 'series_97': ['2010-01-01', '2010-04-10'], 'series_98':
    ['2010-01-01', '2010-04-10'], 'series_99': ['2010-01-01', '2010-04-10'] 
Training index type: DatetimeIndex 
Training index frequency: D 
Regressor parameters: 
    {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False} 
fit_kwargs: {} 
Creation date: 2024-10-16 16:57:04 
Last fit date: 2024-10-16 16:57:05 
Skforecast version: 0.14.0 
Python version: 3.12.4 
Forecaster id: None

In [11]:
forecaster.__repr__

<bound method ForecasterAutoregMultiSeries.__repr__ of ============================ 
ForecasterAutoregMultiSeries 
Regressor: LinearRegression() 
Lags: [1 2 3 4 5] 
Window features: None 
Window size: 5 
Series encoding: ordinal 
Series names (levels): 
    series_0, series_1, series_2, series_3, series_4, series_5, series_6, series_7,
    series_8, series_9, series_10, series_11, series_12, series_13, series_14,
    series_15, series_16, series_17, series_18, series_19, series_20, series_21,
    series_22, series_23, series_24, ..., series_75, series_76, series_77,
    series_78, series_79, series_80, series_81, series_82, series_83, series_84,
    series_85, series_86, series_87, series_88, series_89, series_90, series_91,
    series_92, series_93, series_94, series_95, series_96, series_97, series_98,
    series_99 
Exogenous included: True 
Exogenous names: 
    exog_0, exog_1, exog_2, exog_3, exog_4, exog_5, exog_6, exog_7, exog_8, exog_9,
    exog_10, exog_11, exog_12, exog_13, e

In [12]:
def aaa(trab=None):
    b = 1
    return trab, b

In [13]:
x, b = aaa()
x

In [14]:
b

1

In [15]:
from skforecast.ForecasterAutoregMultiVariate import ForecasterAutoregMultiVariate

lags={'l1': 5}
expected = {'l1': None, 'l2': np.array([1, 2, 3, 4, 5])}

forecaster = ForecasterAutoregMultiVariate(
    LinearRegression(), level='l1', lags=lags, steps=2
)
forecaster.lags_names

{'l1': ['l1_lag_1', 'l1_lag_2', 'l1_lag_3', 'l1_lag_4', 'l1_lag_5']}

In [16]:
forecaster.lags

{'l1': array([1, 2, 3, 4, 5])}

In [17]:
import numpy as np

for k in forecaster.lags:
    if lags[k] is None:
        assert forecaster.lags[k] is None
        assert forecaster.lags_names[k] is None
    else:
        np.testing.assert_array_almost_equal(forecaster.lags[k], expected[k])
        assert forecaster.lags_names[k] == [f'lag_{i}' for i in range(1, lags[k] + 1)]

TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

In [30]:
cols_to_create_lags = {'col1': 5, 'col2': None}

cols_to_create_lags.get('col3', None)

In [42]:
series = pd.DataFrame({'l1': pd.Series(np.arange(10)), 
                        'l2': pd.Series(np.arange(100, 110))})
exog = None

forecaster = ForecasterAutoregMultiVariate(LinearRegression(), level='l1',
                                            lags={'l1': 3, 'l2': 3}, 
                                            steps=2, transformer_series=None)
results = forecaster._create_train_X_y(series=series, exog=exog)

{'l1': 'both', 'l2': 'X'}


In [45]:
np.array([[3., 4., 5., 6., 7., 8., 9.]])[1 - 1, :]

array([3., 4., 5., 6., 7., 8., 9.])

In [44]:
pd.Series(np.array([[3., 4., 5., 6., 7., 8., 9.]])[1 - 1, :])

0    3.0
1    4.0
2    5.0
3    6.0
4    7.0
5    8.0
6    9.0
dtype: float64

In [15]:
np.array([[10], [20], [30], [40], [50]])[1] + 5

array([25])

In [53]:
np.array([[6., 7., 8.],
                  [7., 8., 9.]]).transpose()

array([[6., 7.],
       [7., 8.],
       [8., 9.]])

In [20]:
series = pd.DataFrame({'l1': pd.Series(np.arange(10), dtype=float), 
                           'l2': pd.Series(np.arange(50, 60), dtype=float)})
exog = pd.Series(['string'] * 10, name='exog', dtype=str)

forecaster = ForecasterAutoregMultiVariate(LinearRegression(), level='l1',
                                            lags=5, steps=2, transformer_series=None)
forecaster._create_train_X_y(series=series, exog=exog)

[array([[4., 3., 2., 1., 0.],
       [5., 4., 3., 2., 1.],
       [6., 5., 4., 3., 2.],
       [7., 6., 5., 4., 3.]]), array([[54., 53., 52., 51., 50.],
       [55., 54., 53., 52., 51.],
       [56., 55., 54., 53., 52.],
       [57., 56., 55., 54., 53.]])]


c:\Users\jaesc2\GitHub\skforecast\skforecast\utils\utils.py:553: DataTypeWarning: `exog` may contain only `int`, `float` or `category` dtypes. Most machine learning models do not allow other types of values. Fitting the forecaster may fail. 
 You can suppress this warning using: warnings.simplefilter('ignore', category=ValueTypesExogWarning)
  warnings.warn(


(   l1_lag_1  l1_lag_2  l1_lag_3  l1_lag_4  l1_lag_5  l2_lag_1  l2_lag_2  \
 6       4.0       3.0       2.0       1.0       0.0      54.0      53.0   
 7       5.0       4.0       3.0       2.0       1.0      55.0      54.0   
 8       6.0       5.0       4.0       3.0       2.0      56.0      55.0   
 9       7.0       6.0       5.0       4.0       3.0      57.0      56.0   
 
    l2_lag_3  l2_lag_4  l2_lag_5 exog_step_1 exog_step_2  
 6      52.0      51.0      50.0      string      string  
 7      53.0      52.0      51.0      string      string  
 8      54.0      53.0      52.0      string      string  
 9      55.0      54.0      53.0      string      string  ,
 {1: 5    5.0
  6    6.0
  7    7.0
  8    8.0
  Name: l1_step_1, dtype: float64,
  2: 6    6.0
  7    7.0
  8    8.0
  9    9.0
  Name: l1_step_2, dtype: float64},
 ['l1', 'l2'],
 ['l1', 'l2'],
 ['exog'],
 None,
 ['exog'],
 ['l1_lag_1',
  'l1_lag_2',
  'l1_lag_3',
  'l1_lag_4',
  'l1_lag_5',
  'l2_lag_1',
  'l2_lag_2',


In [4]:
import re
import pytest
import numpy as np
import pandas as pd
from skforecast.exceptions import MissingValuesWarning
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from skforecast.preprocessing import TimeSeriesDifferentiator
from skforecast.preprocessing import RollingFeatures
from skforecast.ForecasterAutoregMultiVariate import ForecasterAutoregMultiVariate

# Fixtures
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import data  # to test results when using differentiation

In [22]:
arr = data.to_numpy(copy=True)
diferenciator = TimeSeriesDifferentiator(order=1)
data_diff = diferenciator.fit_transform(arr)

series = pd.DataFrame(
    {'l1': arr,
        'l2': arr},
    index=data.index
)

series_diff = pd.DataFrame(
    
    {'l1': data_diff,
        'l2': data_diff},
    index=data.index
).dropna()

# Simulated exogenous variable
rng = np.random.default_rng(9876)
exog = pd.Series(
    rng.normal(loc=0, scale=1, size=len(data)), index=data.index, name='exog'
)
exog_diff = exog.iloc[1:]
end_train = '2003-03-01 23:59:00'

In [42]:
forecaster_1 = ForecasterAutoregMultiVariate(
    LinearRegression(), level='l1', steps=3, lags=5, transformer_series=None
)
forecaster_2 = ForecasterAutoregMultiVariate(
    LinearRegression(), level='l1', steps=3, lags=5, transformer_series=None, differentiation=1
)

if False:
    forecaster_2.fit(series=series.loc[:end_train], exog=exog.loc[:end_train])

output_1 = forecaster_1._create_train_X_y(
                series = series_diff.loc[:end_train],
                exog   = exog_diff.loc[:end_train]
            )

output_2 = forecaster_2._create_train_X_y(
                series = series.loc[:end_train],
                exog   = exog.loc[:end_train]
            )

In [43]:
output_1[0].head(3)

l1_lag_1  l1_lag_2  l1_lag_3  l1_lag_4  l1_lag_5  l2_lag_1  \
1992-03-01  0.110283  0.019826  0.070384  0.041253 -0.018889  0.110283   
1992-04-01  0.067467  0.110283  0.019826  0.070384  0.041253  0.067467   
1992-05-01 -0.313899  0.067467  0.110283  0.019826  0.070384 -0.313899   

            l2_lag_2  l2_lag_3  l2_lag_4  l2_lag_5  exog_step_1  exog_step_2  \
1992-03-01  0.019826  0.070384  0.041253 -0.018889    -0.337261     0.303042   
1992-04-01  0.110283  0.019826  0.070384  0.041253     0.303042     1.569935   
1992-05-01  0.067467  0.110283  0.019826  0.070384     1.569935     0.175040   

            exog_step_3  
1992-03-01     1.569935  
1992-04-01     0.175040  
1992-05-01    -0.403905

In [44]:
output_2[0].head(3)

l1_lag_1  l1_lag_2  l1_lag_3  l1_lag_4  l1_lag_5  l2_lag_1  \
1992-03-01  0.110283  0.019826  0.070384  0.041253 -0.018889  0.110283   
1992-04-01  0.067467  0.110283  0.019826  0.070384  0.041253  0.067467   
1992-05-01 -0.313899  0.067467  0.110283  0.019826  0.070384 -0.313899   

            l2_lag_2  l2_lag_3  l2_lag_4  l2_lag_5  exog_step_1  exog_step_2  \
1992-03-01  0.019826  0.070384  0.041253 -0.018889    -0.337261     0.303042   
1992-04-01  0.110283  0.019826  0.070384  0.041253     0.303042     1.569935   
1992-05-01  0.067467  0.110283  0.019826  0.070384     1.569935     0.175040   

            exog_step_3  
1992-03-01     1.569935  
1992-04-01     0.175040  
1992-05-01    -0.403905

In [45]:
output_1[1][1].head(3)

1992-01-01    0.067467
1992-02-01   -0.313899
1992-03-01    0.025128
Freq: MS, Name: l1_step_1, dtype: float64

In [46]:
output_2[1][1].head(3)

1992-01-01    0.067467
1992-02-01   -0.313899
1992-03-01    0.025128
Freq: MS, Name: l1_step_1, dtype: float64

In [47]:
pd.testing.assert_frame_equal(output_1[0], output_2[0])
assert output_1[1].keys() == output_2[1].keys()
for key in output_1[1]: 
    pd.testing.assert_series_equal(output_1[1][key], output_2[1][key]) 
assert output_1[2] == output_2[2]
assert output_1[3] == output_2[3]
assert output_1[4] == output_2[4]
assert output_1[5] == output_2[5]
assert output_1[6] == output_2[6]
assert output_1[7] == output_2[7]
for k in output_1[8].keys():
    assert output_1[8][k] == output_2[8][k]

In [28]:
from skforecast.ForecasterAutoregDirect import ForecasterAutoregDirect
from skforecast.ForecasterAutoreg import ForecasterAutoreg
from skforecast.preprocessing import RollingFeatures

y_datetime = pd.Series(
    np.arange(15), index=pd.date_range('2000-01-01', periods=15, freq='D'),
    name='y', dtype=float
)
exog_datetime = pd.Series(
    np.arange(100, 115), index=pd.date_range('2000-01-01', periods=15, freq='D'),
    name='exog', dtype=float
)
rolling = RollingFeatures(stats=['mean', 'median'], window_sizes=[5, 5])
rolling_2 = RollingFeatures(stats='sum', window_sizes=[6])

forecaster = ForecasterAutoreg(
    LinearRegression(), lags=5, window_features=[rolling, rolling_2],
    differentiation=1
)
forecaster.fit(y=y_datetime)

c:\Users\jaesc2\Miniconda3\envs\skforecast_py12\Lib\site-packages\sklearn\preprocessing\_discretization.py:263: UserWarning: Feature 0 is constant and will be replaced with 0.
  warnings.warn(


In [36]:
from skforecast.ForecasterAutoregDirect.tests.fixtures_ForecasterAutoregDirect import data  # to test results when using differentiation

end_train = '2003-03-01 23:59:00'

# Simulated exogenous variable
rng = np.random.default_rng(9876)
exog = pd.Series(
    rng.normal(loc=0, scale=1, size=len(data)), index=data.index, name='exog'
)
steps = len(data.loc[end_train:])

forecaster = ForecasterAutoregDirect(
                    regressor       = LinearRegression(),
                    steps           = 5,
                    lags            = 15,
                    differentiation = 1
            )
forecaster.fit(y=data.loc[:end_train], exog=exog.loc[:end_train])
results = forecaster._create_predict_inputs(exog=exog.loc[end_train:])
results

([array([[ 0.07503713, -0.48984868, -0.01463081,  0.10597971, -0.01018012,
           0.02377842,  0.09883014,  0.01630394,  0.17596768, -0.00584249,
           0.09807633,  0.04869748,  0.07558021, -0.56028323,  0.14355438,
           1.16172882]]),
  array([[ 0.07503713, -0.48984868, -0.01463081,  0.10597971, -0.01018012,
           0.02377842,  0.09883014,  0.01630394,  0.17596768, -0.00584249,
           0.09807633,  0.04869748,  0.07558021, -0.56028323,  0.14355438,
           0.29468848]]),
  array([[ 0.07503713, -0.48984868, -0.01463081,  0.10597971, -0.01018012,
           0.02377842,  0.09883014,  0.01630394,  0.17596768, -0.00584249,
           0.09807633,  0.04869748,  0.07558021, -0.56028323,  0.14355438,
          -0.4399757 ]]),
  array([[ 0.07503713, -0.48984868, -0.01463081,  0.10597971, -0.01018012,
           0.02377842,  0.09883014,  0.01630394,  0.17596768, -0.00584249,
           0.09807633,  0.04869748,  0.07558021, -0.56028323,  0.14355438,
           1.25008389]

In [2]:
from itertools import chain

lags_ = {'l1': None, 'l2': None}

n_lags = len(list(
    chain(*[v for v in lags_.values() if v is not None])
))
n_lags

0

In [3]:
import pandas as pd

type(pd.to_datetime('2020-01-01'))

pandas._libs.tslibs.timestamps.Timestamp

In [4]:
import re
import pytest
import numpy as np
import pandas as pd
from sklearn.exceptions import NotFittedError
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LinearRegression
from skforecast.preprocessing import RollingFeatures
from sklearn.ensemble import HistGradientBoostingRegressor
from skforecast.ForecasterAutoregMultiVariate import ForecasterAutoregMultiVariate

# Fixtures
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import series
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import exog
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import exog_predict
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import data

In [82]:
end_train = '2003-03-01 23:59:00'
arr = data.to_numpy(copy=True)
series = pd.DataFrame(
    {'l1': arr,
        'l2': arr},
    index=data.index
)

# Simulated exogenous variable
rng = np.random.default_rng(9876)
exog = pd.Series(
    rng.normal(loc=0, scale=1, size=len(data)), index=data.index, name='exog'
)

forecaster = ForecasterAutoregMultiVariate(
                    regressor       = LinearRegression(),
                    level           = 'l1',
                    steps           = 5,
                    lags            = 15,
                    differentiation = 1,
                    transformer_series = StandardScaler()
            )
forecaster.fit(series=series.loc[:end_train], exog=exog.loc[:end_train])
results = forecaster._create_predict_inputs(exog=exog.loc[end_train:])

In [84]:
forecaster = ForecasterAutoregMultiVariate(
                    regressor       = LinearRegression(),
                    level           = 'l1',
                    steps           = 5,
                    lags            = {'l1': None, 'l2': None},
                    differentiation = 1,
                    transformer_series = StandardScaler()
            )

ValueError: At least one of the arguments `lags` or `window_features` must be different from None. This is required to create the predictors used in training the forecaster.

In [87]:
my_dict = {'l1': None, 'l2': np.array([1])}

all(value is None for value in my_dict.values())

False

In [63]:
random_state = 123
np.random.seed(random_state)

n_size = 100
residuals = {
    1: np.random.normal(loc=0, scale=1, size=n_size),
    2: np.random.normal(loc=0, scale=1, size=n_size),
    3: np.random.normal(loc=0, scale=1, size=n_size),
    4: np.random.normal(loc=0, scale=1, size=n_size),
    5: np.random.normal(loc=0, scale=1, size=n_size),
}
# residuals = {
#     1: np.array([10] * n_size),
#     2: np.array([20] * n_size),
#     3: np.array([30] * n_size),
#     4: np.array([40] * n_size),
#     5: np.array([50] * n_size)
# }

steps = np.arange(1, 6)

n_boot = 150
predictions = np.random.normal(loc=0, scale=1, size=len(steps))
boot_predictions = np.tile(predictions, (n_boot, 1)).T

In [68]:
rng = np.random.default_rng(seed=random_state)
for i, step in enumerate(steps):
    sampled_residuals = residuals[step][
        rng.integers(low=0, high=len(residuals[step]), size=n_boot)
    ]
    boot_predictions[i, :] = boot_predictions[i, :] + sampled_residuals

In [65]:
random_state = 123
np.random.seed(random_state)

n_size = 100
residuals = {
    1: np.random.normal(loc=0, scale=1, size=n_size),
    2: np.random.normal(loc=0, scale=1, size=n_size),
    3: np.random.normal(loc=0, scale=1, size=n_size),
    4: np.random.normal(loc=0, scale=1, size=n_size),
    5: np.random.normal(loc=0, scale=1, size=n_size),
}
# residuals = {
#     1: np.array([10] * n_size),
#     2: np.array([20] * n_size),
#     3: np.array([30] * n_size),
#     4: np.array([40] * n_size),
#     5: np.array([50] * n_size)
# }

steps = np.arange(1, 6)

n_boot = 150
predictions = np.random.normal(loc=0, scale=1, size=len(steps))
boot_predictions = np.tile(predictions, (n_boot, 1)).T

In [92]:
from lightgbm import LGBMRegressor

from skforecast.preprocessing import RollingFeatures
from skforecast.ForecasterAutoregMultiVariate import ForecasterAutoregMultiVariate

# Fixtures
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import series as series_2
from skforecast.ForecasterAutoregMultiVariate.tests.fixtures_ForecasterAutoregMultiVariate import exog as exog_2

rolling = RollingFeatures(stats=['mean', 'sum'], window_sizes=[3, 5])
forecaster = ForecasterAutoregMultiVariate(
                    regressor       = LGBMRegressor(verbose=-1, random_state=123),
                    level           = 'l1',
                    steps           = 2,
                    lags            = 3,
                    window_features = rolling
                )
forecaster.fit(series=series_2, exog=exog_2['exog_1'])
results = forecaster.get_feature_importances(step=2, sort_importance=False)
results

feature  importance
0         l1_lag_1           0
1         l1_lag_2          18
2         l1_lag_3          11
3   l1_roll_mean_3           0
4    l1_roll_sum_5          19
5         l2_lag_1          12
6         l2_lag_2           9
7         l2_lag_3           8
8   l2_roll_mean_3           7
9    l2_roll_sum_5           3
10          exog_1          13

In [93]:
results['feature'].to_list()

['l1_lag_1',
 'l1_lag_2',
 'l1_lag_3',
 'l1_roll_mean_3',
 'l1_roll_sum_5',
 'l2_lag_1',
 'l2_lag_2',
 'l2_lag_3',
 'l2_roll_mean_3',
 'l2_roll_sum_5',
 'exog_1']

In [94]:
results['importance'].to_numpy()

array([ 0, 18, 11,  0, 19, 12,  9,  8,  7,  3, 13], dtype=int32)