In [1]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
sys.path.insert(1, str(Path.cwd().parent))
str(Path.cwd().parent)

'c:\\Users\\jaesc2\\GitHub\\skforecast'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error

from skforecast.datasets import fetch_dataset
from skforecast.ForecasterAutoregMultiSeries import ForecasterAutoregMultiSeries
from skforecast.model_selection_multiseries import backtesting_forecaster_multiseries
from skforecast.model_selection_multiseries import grid_search_forecaster_multiseries
from skforecast.model_selection_multiseries import bayesian_search_forecaster_multiseries
from skforecast.utils import transform_numpy
from skforecast.utils import transform_series
from skforecast.utils import transform_dataframe

In [3]:
input_1 = np.array([1.16, -0.28, 0.07, 2.4, 0.25, -0.56, -1.42, 1.26, 1.78, -1.49])
transformer = StandardScaler()
transformer.fit(input_1.reshape(-1, 1))

input_2 = transformer.transform(input_1.reshape(-1, 1)).flatten()
results = transform_numpy(
                  array             = input_2,
                  transformer       = transformer,
                  fit               = False,
                  inverse_transform = True
              )
results

array([ 1.16, -0.28,  0.07,  2.4 ,  0.25, -0.56, -1.42,  1.26,  1.78,
       -1.49])

In [4]:
input_array = np.array(['A'] * 5 + ['B'] * 5).reshape(-1, 1)
transformer = OneHotEncoder(sparse_output=False)
transformer.fit_transform(input_array)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [5]:
array = np.array([
                [7.5, 'a'],
                [24.4, 'a'],
                [60.3, 'a'],
                [57.3, 'a'],
                [50.7, 'b'],
                [41.4, 'b'],
                [87.2, 'b'],
                [47.4, 'b']
            ], dtype=object)
input_1 = np.array([1.16, -0.28, 0.07, 2.4, 0.25, -0.56, -1.42, 1.26, 1.78, -1.49])
input_1 = input_1.reshape(-1, 1)
transformer = ColumnTransformer(
                    [('scale', StandardScaler(), [0]),
                    ('onehot', OneHotEncoder(sparse_output=False), [1])],
                    remainder = 'passthrough',
                    verbose_feature_names_out = False
                  )
transformer.fit_transform(input_1)

ValueError: all features must be in [0, 0] or [-1, 0]

In [7]:
input_1

array([[ 1.16],
       [-0.28],
       [ 0.07],
       [ 2.4 ],
       [ 0.25],
       [-0.56],
       [-1.42],
       [ 1.26],
       [ 1.78],
       [-1.49]])

In [6]:
results = transform_numpy(
                  array             = array,
                  transformer       = transformer,
                  fit               = True,
                  inverse_transform = False
              )
results

array([[-1.76425513,  1.        ,  0.        ],
       [-1.00989936,  1.        ,  0.        ],
       [ 0.59254869,  1.        ,  0.        ],
       [ 0.45863938,  1.        ,  0.        ],
       [ 0.1640389 ,  0.        ,  1.        ],
       [-0.25107995,  0.        ,  1.        ],
       [ 1.79326881,  0.        ,  1.        ],
       [ 0.01673866,  0.        ,  1.        ]])

In [24]:
results.flatten()

array([ 0.67596768, -0.47871021, -0.19805933,  1.67027365, -0.0537246 ,
       -0.70323091, -1.39283021,  0.75615365,  1.17312067, -1.44896038])

In [6]:
input_1 = pd.Series(
    np.array([1.16, -0.28, 0.07, 2.4, 0.25, -0.56, -1.42, 1.26, 1.78, -1.49]),
    name = 'y'
).to_frame()
transformer = StandardScaler()
transformer.fit(input_1)
print(transformer.feature_names_in_)

# input_2

# input_2 = transformer.transform(input_1.to_numpy().reshape(-1, 1)).flatten()
# input_2

['y']


In [9]:

results = transform_numpy(
                  array             = np.array([1, 3]),
                  transformer       = transformer,
                  fit               = False,
                  inverse_transform = False
              )
results

array([0.54767014, 2.15138944])